# Generated by Django 3.2.3 on 2021-06-02 16:49

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app.migrations.0003_auto_20210531_1410


def create_tokens(apps, schema_editor):
    TokenData = apps.get_model('app', 'TokenData')
    TokenData.objects.bulk_create([TokenData(title='Painting #{}'.format(i + 1)) for i in range(10000)])

class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_alter_tokendata_image'), ('app', '0003_auto_20210531_1410'), ('app', '0004_auto_20210602_1949')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RunPython(
            code=create_tokens,
        ),
    ]
